import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default:"NextJS Journey",
    template:"%s | NextJS Journey"
  },
  description: "Generated by create next app",
};
/*
* Metadata  can be defined in layout and the page ,if both are present the page replaces the metadata of layout if they have same property.
 Metadata is of two type static and dynamic.
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
<Header/>
        <div className="h-96">{children}</div>
<Footer/>
      </body>
          
    </html>
  );
}
